### ISSUE TITLE
Select on connection close channel to prevent sending to a closed connection

### ISSUE THREAD

**Issue by antoniomika** [antoniomika/sish#3]
Recent error found in demo instance:
```
panic: send on closed channel

goroutine 4128 [running]:
main.main.func4.1(0xc00024f380, 0xc000150880)
	/usr/local/go/src/github.com/antoniomika/sish/main.go:152 +0xa1
created by main.main.func4
	/usr/local/go/src/github.com/antoniomika/sish/main.go:142 +0x2d2
```
In regards to this change:

https://github.com/antoniomika/sish/blob/cc916eb8657358692c3f5d297742e1e602c58f08/main.go#L142-L156

A quick fix for this would be to change this function to have
```go
select {
case <-holderConn.Close:
	return
default:
	holderConn.Messages <- "No forwarding requests sent. Closing connection."
	time.Sleep(1 * time.Millisecond)
	holderConn.CleanUp(state)
}
```
or similar. A quick fix in the meantime would be to start the process with `-sish.cleanupunbound=false`

**Comment by antoniomika** [comment]
Resolved by: afba880
