### ISSUE TITLE
Frequent client connections cause panic due to a concurrent channel close.

### ISSUE THREAD

**Issue by antoniomika** [antoniomika/sish#78]
During testing with frequent and fast client connections and disconnects a panic condition was experienced in the CleanUp function where an already closed channel was trying to be closed. This commit adds handling for this condition but doesn't address the root cause.

```
host1 sish: 2020/02/xx xx:xx:xx Closed SSH connection for: client.ip:39204 user: client.username
host1 sish: 2020/02/xx xx:xx:xx Waited for ssh conn without session: ssh: disconnect, reason 11: disconnected by user
host1 sish: panic: close of closed channel
host1 sish: goroutine 428 [running]:
host1 sish: main.(*SSHConnection).CleanUp(0xc000148900, 0xc000154f90)
host1 sish: /home/runner/work/sish/sish/main.go:333 +0x36
host1 sish: main.checkSession(0xc000148a40, 0xc000148900, 0xc000154f90)
host1 sish: /home/runner/work/sish/sish/handle.go:51 +0x185
host1 sish: created by main.handleRequest
host1 sish: /home/runner/work/sish/sish/handle.go:23 +0x1d5
```
Original PR: #75

**Comment by antoniomika** [comment]
@athena-metis I fixed this issue in #85. I'm gonna close this now as I'll be merging #86 (which solves the issue) in today after I've made some documentation changes.
